### ISSUE TITLE
chore: use code in github.com instead of code.google.com

### ISSUE THREAD

**Issue by yanyiwu** [goraft/raft#246]
For example:
https://github.com/goraft/raft/pull/245

use github.com/golang/protobuf and github.com/gogo/protobuf instead of code.google.com/p/gogoprotobuf and code.google.com/p/goprotobuf

I think github.com is more convenient than code.google.com , espercially for programmer in China .

**Comment by benbjohnson** [comment]
@chrislusf as @philips mentioned, this repo is currently unmaintained. You can submit a PR for the change or you can fork this repo and maintain changes in your fork.
