### ISSUE TITLE
Please link to alternative Raft implementations

### ISSUE THREAD

**Issue by joeshaw** [goraft/raft#248]
The README currently says:

> The original project authors have created new raft implementations now used in etcd and InfluxDB.

Can you add links to those new implementations in the README?  The one I know about is https://github.com/hashicorp/raft.  Are there others?

**Comment by yichengq** [comment]
I think @xiang90 is working on https://github.com/coreos/etcd/tree/master/raft, and @benbjohnson is working on https://github.com/influxdb/influxdb/tree/master/raft

**Comment by philips** [comment]
@joeshaw links added. Thanks.
