### ISSUE TITLE
goraft seems not deal with read consistency problem

### ISSUE THREAD

**Issue by ghost** [goraft/raft#249]
etcd have Read consistency flag, How goraft deal with that problem?

**Comment by benbjohnson** [comment]
This repo is no longer maintained and etcd uses a different raft implementation.

**Comment by ghost** [comment]
some project like seaweedfs use goraft is not safe？

**Comment by philips** [comment]
@better0332 there are known issues with go-raft. I would not suggest using go-raft for production use. See an alternative here: https://godoc.org/github.com/coreos/etcd/raft
